# Generated by Django 4.2.7 on 2023-12-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee-cashier', 'Employee-Cashier'), ('employee-salesman', 'Employee-Salesman'), ('employee-manager', 'Employee-Manager'), ('vendor', 'Vendor'), ('customer', 'Customer')], max_length=20),
        ),
    ]
