# Generated by Django 4.2.7 on 2024-01-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('medicine_id', 'branch')},
        ),
    ]
