# Generated by Django 4.2.7 on 2024-01-25 10:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('total', models.IntegerField()),
                ('type', models.CharField(choices=[('purchase', 'purchase'), ('sales', 'sales')], max_length=20)),
                ('order_from_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order_to_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order_from_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_from_content_type', to='contenttypes.contenttype')),
                ('order_to_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_to_content_type', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(unique=True)),
                ('price', models.FloatField()),
                ('line_total', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('medicine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
