# Generated by Django 4.2.7 on 2024-01-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_from_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_to_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
