# Generated by Django 4.2.7 on 2024-01-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_order_from_id_alter_orders_order_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
