# Generated by Django 4.2.7 on 2024-01-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0003_alter_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelines',
            name='medicine_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine'),
        ),
        migrations.AlterField(
            model_name='medicinelines',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinelines',
            unique_together={('order', 'line_no')},
        ),
    ]
