# Generated by Django 4.2.7 on 2024-01-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_unique_together'),
        ('orders', '0004_alter_medicinelines_medicine_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicinelines',
            unique_together={('order', 'medicine_id')},
        ),
    ]
