# Generated by Django 4.2.7 on 2024-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_medicinelines_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelines',
            name='line_no',
            field=models.IntegerField(),
        ),
    ]
